# Generated by Django 5.2.9 on 2026-07-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="product_biz_active_avail_idx",
            old_name="product_business_active_avail_idx",
        ),
    ]
