# Generated by Django 5.2.9 on 2026-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "businesses",
            "0002_rename_product_business_active_avail_idx_product_biz_active_avail_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/images/",
                verbose_name="image",
            ),
        ),
    ]
