# Generated by Django 5.2.9 on 2026-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="typical_delivery_time",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. '30-45 mins'. Shown to customers before ordering.",
                max_length=50,
                verbose_name="typical delivery time",
            ),
        ),
    ]
