# Generated by Django 5.2.9 on 2026-08-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anythingrequest",
            name="request_text",
            field=models.TextField(
                blank=True,
                help_text="What does the customer want?",
                verbose_name="request text",
            ),
        ),
    ]
