# Generated by Django 5.2.9 on 2026-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_anythingrequest_request_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed_eta",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. '45 mins'. Set by admin when accepting the order.",
                max_length=50,
                verbose_name="confirmed ETA",
            ),
        ),
    ]
