# Generated by Django 5.2.9 on 2026-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_confirmed_eta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="label",
            field=models.CharField(max_length=50, verbose_name="label"),
        ),
    ]
