# Generated by Django 5.2.9 on 2026-08-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_deliveryaddress_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anythingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("quoted", "Quoted"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("ordered", "Converted to Order"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
