# Generated by Django 6.0.7 on 2026-07-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "businesses",
            "0002_rename_product_business_active_avail_idx_product_biz_active_avail_idx",
        ),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Displayed as alt-text / accessibility label.",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="promotions/banners/", verbose_name="image"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("business", "Business"),
                            ("category", "Category"),
                            ("product", "Product"),
                            ("technician", "Technician"),
                            ("external", "External URL"),
                        ],
                        default="external",
                        max_length=20,
                        verbose_name="target type",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="PK of the linked object (leave blank for external URL).",
                        null=True,
                        verbose_name="target ID",
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="External URL to open in a WebView (used when target_type=external).",
                        verbose_name="target URL",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Banner is hidden before this date. Leave blank to show immediately.",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Banner is hidden after this date. Leave blank to show indefinitely.",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first in the carousel.",
                        verbose_name="sort order",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which village/city this banner appears in. Leave blank to make it a global fallback for all locations.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banners",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "banner",
                "verbose_name_plural": "banners",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "is_active"],
                        name="banner_location_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g. 15.00) or fixed amount (e.g. 10.00).",
                        max_digits=8,
                        verbose_name="discount value",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Offer is inactive before this date.",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Offer is inactive after this date.",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="businesses.business",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which products this offer applies to. Leave empty to apply to all business products.",
                        related_name="offers",
                        to="businesses.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "offer",
                "verbose_name_plural": "offers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "is_active"],
                        name="offer_business_active_idx",
                    )
                ],
            },
        ),
    ]
