# Generated by Django 5.2.9 on 2026-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_business_typical_delivery_time"),
        ("promotions", "0001_add_banner_offer_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotDeal",
            fields=[],
            options={
                "verbose_name": "hot deal",
                "verbose_name_plural": "hot deals",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("businesses.product",),
        ),
        migrations.AddField(
            model_name="banner",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secondary text displayed below the main title.",
                max_length=200,
                verbose_name="subtitle",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="tag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A short highlight label (e.g., 'New', 'Hot', 'Sale').",
                max_length=50,
                verbose_name="tag",
            ),
        ),
    ]
