"""
Django Admin configuration for the notifications app.

  - DeviceToken: inspection-only. Admins can see registered tokens per user
    and delete stale ones. No manual creation.
  - Notification: read-only log. Admins can inspect what was sent to users.
    No manual creation (notifications are always generated by Celery tasks).
"""

from django.contrib import admin
from django.utils.translation import gettext_lazy as _

from notifications.models import DeviceToken, Notification


@admin.register(DeviceToken)
class DeviceTokenAdmin(admin.ModelAdmin):
    """
    Inspection view for FCM device tokens.
    Useful for debugging push delivery issues (e.g., user not receiving pushes).
    """

    list_display = ("id", "user", "device_type", "token_preview", "created_at", "updated_at")
    list_filter = ("device_type",)
    search_fields = ("user__phone", "user__name", "token")
    readonly_fields = ("user", "token", "device_type", "created_at", "updated_at")
    ordering = ("-updated_at",)

    def has_add_permission(self, request):
        """Tokens are registered by the mobile app only."""
        return False

    def has_change_permission(self, request, obj=None):
        """Tokens should not be modified by hand."""
        return False

    @admin.display(description="Token (preview)")
    def token_preview(self, obj):
        return obj.token[:30] + "…" if len(obj.token) > 30 else obj.token


@admin.register(Notification)
class NotificationAdmin(admin.ModelAdmin):
    """
    Read-only log of all in-app notifications.
    Useful for auditing what was delivered to a user and debugging push issues.
    """

    list_display = (
        "id",
        "user",
        "type",
        "title",
        "is_read",
        "created_at",
    )
    list_filter = ("type", "is_read", "created_at")
    search_fields = ("user__phone", "user__name", "title", "body")
    readonly_fields = (
        "user",
        "title",
        "body",
        "type",
        "data",
        "is_read",
        "created_at",
        "updated_at",
    )
    ordering = ("-created_at",)

    fieldsets = (
        (None, {
            "fields": ("user", "type", "title", "body"),
        }),
        (_("Payload & State"), {
            "fields": ("data", "is_read"),
        }),
        (_("Timestamps"), {
            "fields": ("created_at", "updated_at"),
            "classes": ("collapse",),
        }),
    )

    def has_add_permission(self, request):
        """Notifications are always created by Celery tasks."""
        return False

    def has_change_permission(self, request, obj=None):
        """Notifications are immutable records."""
        return False
