# Generated by Django 5.2.9 on 2026-08-01 00:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="technician_categories/icons/",
                        verbose_name="icon",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first in the category list.",
                        verbose_name="sort order",
                    ),
                ),
            ],
            options={
                "verbose_name": "technician category",
                "verbose_name_plural": "technician categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="technicians/photos/",
                        verbose_name="photo",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Internal use only — NEVER expose this to customers.",
                        max_length=20,
                        verbose_name="phone",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short description of the technician's expertise and experience.",
                        verbose_name="bio / description",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="years of experience"
                    ),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="average rating",
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="review count"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured technicians may appear in the homepage popular section.",
                        verbose_name="is featured",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technicians",
                        to="locations.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technicians",
                        to="technicians.techniciancategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "technician",
                "verbose_name_plural": "technicians",
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="TechnicianRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Customer's description of the problem or additional context.",
                        verbose_name="notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes visible only to admin (e.g. technician feedback, scheduling info).",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        help_text="The customer's address where the technician should visit.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technician_requests",
                        to="orders.deliveryaddress",
                        verbose_name="service address",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="technicians.technician",
                        verbose_name="technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "technician request",
                "verbose_name_plural": "technician requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="technician",
            index=models.Index(
                fields=["location", "is_active"], name="technician_location_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technician",
            index=models.Index(
                fields=["category", "is_active"], name="technician_category_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicianrequest",
            index=models.Index(
                fields=["customer", "status"], name="techreq_customer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="technicianrequest",
            index=models.Index(
                fields=["technician", "status"], name="techreq_technician_status_idx"
            ),
        ),
    ]
