# Generated by Django 5.2.9 on 2026-08-01 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pickup_location",
                    models.TextField(
                        help_text="Free-text description, e.g. 'Next to the main mosque in Arab El-Raml'.",
                        verbose_name="pickup location",
                    ),
                ),
                (
                    "pickup_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Optional GPS latitude for precise pickup pinning.",
                        max_digits=9,
                        null=True,
                        verbose_name="pickup latitude",
                    ),
                ),
                (
                    "pickup_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Optional GPS longitude for precise pickup pinning.",
                        max_digits=9,
                        null=True,
                        verbose_name="pickup longitude",
                    ),
                ),
                (
                    "destination",
                    models.TextField(
                        help_text="Free-text description of where the customer wants to go.",
                        verbose_name="destination",
                    ),
                ),
                (
                    "destination_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Optional GPS latitude for precise destination pinning.",
                        max_digits=9,
                        null=True,
                        verbose_name="destination latitude",
                    ),
                ),
                (
                    "destination_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Optional GPS longitude for precise destination pinning.",
                        max_digits=9,
                        null=True,
                        verbose_name="destination longitude",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("tuk_tuk", "Tuk-Tuk"), ("car", "Car")],
                        default="tuk_tuk",
                        max_length=20,
                        verbose_name="vehicle type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional context from the customer (e.g. number of passengers, luggage).",
                        verbose_name="notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes visible only to admin (e.g. driver name, ETA, reason for rejection).",
                        verbose_name="admin notes",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "ride request",
                "verbose_name_plural": "ride requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="ridereq_customer_status_idx",
                    )
                ],
            },
        ),
    ]
