# Generated by Django 5.2.9 on 2026-08-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_add_riderequest_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
